export default function Dmy3() {
  const elements = [
    { bg: "bg-blue-300", n: 1, s: "H", name: "Hydrogen", row: 1, col: 1 },
    { bg: "bg-purple-950", n: 2, s: "He", name: "Helium", row: 1, col: 18 },
    { bg: "bg-pink-300", n: 3, s: "Li", name: "Lithium", row: 2, col: 1 },
    { bg: "bg-orange-300 ", n: 4, s: "Be", name: "Beryllium", row: 2, col: 2 },
    { bg: "bg-blue-300", n: 5, s: "B", name: "Boron", row: 2, col: 13 },
    { bg: "bg-blue-500", n: 6, s: "C", name: "Carbon", row: 2, col: 14 },
    { bg: "bg-blue-500", n: 7, s: "N", name: "Nitrogen", row: 2, col: 15 },
    { bg: "bg-blue-500", n: 8, s: "O", name: "Oxygen", row: 2, col: 16 },
    { bg: "bg-purple-800", n: 9, s: "F", name: "Fluorine", row: 2, col: 17 },
    { bg: "bg-purple-950", n: 10, s: "Ne", name: "Neon", row: 2, col: 18 },
    { bg: "bg-pink-300", n: 11, s: "Na", name: "Sodium", row: 3, col: 1 },
    { bg: "bg-orange-300 ", n: 12, s: "Mg", name: "Magnesium", row: 3, col: 2 },
    { bg: "bg-green-300 ", n: 13, s: "Al", name: "Aluminium", row: 3, col: 13 },
    { bg: "bg-blue-300", n: 14, s: "Si", name: "Silicon", row: 3, col: 14 },
    { bg: "bg-blue-500", n: 15, s: "P", name: "Phosphorus", row: 3, col: 15 },
    { bg: "bg-blue-500", n: 16, s: "S", name: "Sulfur", row: 3, col: 16 },
    { bg: "bg-purple-800", n: 17, s: "Cl", name: "Chlorine", row: 3, col: 17 },
    { bg: "bg-purple-950", n: 18, s: "Ar", name: "Argon", row: 3, col: 18 },
    { bg: "bg-pink-300", n: 19, s: "K", name: "Potassium", row: 4, col: 1 },
    { bg: "bg-orange-300", n: 20, s: "Ca", name: "Calcium", row: 4, col: 2 },
    { bg: "bg-yellow-400 ", n: 21, s: "Sc", name: "Scandium", row: 4, col: 3 },
    { bg: "bg-yellow-400 ", n: 22, s: "Ti", name: "Titanium", row: 4, col: 4 },
    { bg: "bg-yellow-400 ", n: 23, s: "V", name: "Vanadium", row: 4, col: 5 },
    { bg: "bg-yellow-400 ", n: 24, s: "Cr", name: "Chromium", row: 4, col: 6 },
    { bg: "bg-yellow-400 ", n: 25, s: "Mn", name: "Manganese", row: 4, col: 7 },
    { bg: "bg-yellow-400 ", n: 26, s: "Fe", name: "Iron", row: 4, col: 8 },
    { bg: "bg-yellow-400 ", n: 27, s: "Co", name: "Cobalt", row: 4, col: 9 },
    { bg: "bg-yellow-400 ", n: 28, s: "Ni", name: "Nickel", row: 4, col: 10 },
    { bg: "bg-yellow-400 ", n: 29, s: "Cu", name: "Copper", row: 4, col: 11 },
    { bg: "bg-yellow-400 ", n: 30, s: "Zn", name: "Zinc", row: 4, col: 12 },
    { bg: "bg-green-300 ", n: 31, s: "Ga", name: "Gallium", row: 4, col: 13 },
    { bg: "bg-blue-300", n: 32, s: "Ge", name: "Germanium", row: 4, col: 14 },
    { bg: "bg-blue-300", n: 33, s: "As", name: "Arsenic", row: 4, col: 15 },
    { bg: "bg-blue-500", n: 34, s: "Se", name: "Selenium", row: 4, col: 16 },
    { bg: "bg-purple-800", n: 35, s: "Br", name: "Bromine", row: 4, col: 17 },
    { bg: "bg-purple-950", n: 36, s: "Kr", name: "Krypton", row: 4, col: 18 },
    { bg: "bg-pink-300", n: 37, s: "Rb", name: "Rubidium", row: 5, col: 1 },
    { bg: "bg-orange-300", n: 38, s: "Sr", name: "Strontium", row: 5, col: 2 },
    { bg: "bg-yellow-400 ", n: 39, s: "Y", name: "Yttrium", row: 5, col: 3 },
    { bg: "bg-yellow-400 ", n: 40, s: "Zr", name: "Zirconium", row: 5, col: 4 },
    { bg: "bg-yellow-400 ", n: 41, s: "Nb", name: "Niobium", row: 5, col: 5 },
    {
      bg: "bg-yellow-400 ",
      n: 42,
      s: "Mo",
      name: "Molybdenum",
      row: 5,
      col: 6,
    },
    {
      bg: "bg-yellow-400 ",
      n: 43,
      s: "Tc",
      name: " Technetium",
      row: 5,
      col: 7,
    },
    {
      bg: "bg-yellow-400 ",
      n: 44,
      s: "Ru ",
      name: " Ruthenium",
      row: 5,
      col: 8,
    },
    { bg: "bg-yellow-400 ", n: 45, s: "Rh", name: " Rhodium", row: 5, col: 9 },
    {
      bg: "bg-yellow-400 ",
      n: 46,
      s: " Pd",
      name: " Palladium",
      row: 5,
      col: 10,
    },
    { bg: "bg-yellow-400 ", n: 47, s: "Ag ", name: " Silver", row: 5, col: 11 },
    {
      bg: "bg-yellow-400 ",
      n: 48,
      s: "Cd ",
      name: "Cadmium ",
      row: 5,
      col: 12,
    },
    { bg: "bg-green-300 ", n: 49, s: "In ", name: "Indium ", row: 5, col: 13 },
    { bg: "bg-green-300 ", n: 50, s: "Sn ", name: "Tin ", row: 5, col: 14 },
    { bg: "bg-blue-300", n: 51, s: " Sb", name: "Antimony ", row: 5, col: 15 },
    { bg: "bg-blue-300", n: 52, s: " Te", name: "Tellurium ", row: 5, col: 16 },
    { bg: "bg-purple-800", n: 53, s: " I", name: " Iodine", row: 5, col: 17 },
    { bg: "bg-purple-950", n: 54, s: " Xe", name: "Xenon ", row: 5, col: 18 },
    { bg: "bg-pink-300", n: 55, s: "Cs ", name: "Caesium ", row: 6, col: 1 },
    { bg: "bg-orange-300", n: 56, s: "Ba ", name: "Barium ", row: 6, col: 2 },
    { bg: "bg-purple-500 ", n: "", s: "57-71 ", name: " ", row: 6, col: 3 },
    { bg: "bg-yellow-400 ", n: 72, s: "Hf ", name: "Hafnium ", row: 6, col: 4 },
    {
      bg: "bg-yellow-400 ",
      n: 73,
      s: "Ta ",
      name: "Tantalum ",
      row: 6,
      col: 5,
    },
    { bg: "bg-yellow-400 ", n: 74, s: "W ", name: "Tungsten ", row: 6, col: 6 },
    { bg: "bg-yellow-400 ", n: 75, s: "Re ", name: "Rhenium ", row: 6, col: 7 },
    { bg: "bg-yellow-400 ", n: 76, s: "Os ", name: "Osmium ", row: 6, col: 8 },
    { bg: "bg-yellow-400 ", n: 77, s: "Ir ", name: "Iridium ", row: 6, col: 9 },
    {
      bg: "bg-yellow-400 ",
      n: 78,
      s: "Pt ",
      name: "Platinum ",
      row: 6,
      col: 10,
    },
    { bg: "bg-yellow-400 ", n: 79, s: "Au ", name: "Gold ", row: 6, col: 11 },
    {
      bg: "bg-yellow-400 ",
      n: 80,
      s: " Hg",
      name: "Mercury ",
      row: 6,
      col: 12,
    },
    {
      bg: "bg-green-300 ",
      n: 81,
      s: " Tl",
      name: "Thallium ",
      row: 6,
      col: 13,
    },
    { bg: "bg-green-300 ", n: 82, s: "Pb ", name: "Lead ", row: 6, col: 14 },
    { bg: "bg-green-300 ", n: 83, s: "Bi ", name: " Bismuth", row: 6, col: 15 },
    { bg: "bg-blue-300", n: 84, s: "Po ", name: "Polonium ", row: 6, col: 16 },
    {
      bg: "bg-purple-800",
      n: 85,
      s: "At ",
      name: "Astatine ",
      row: 6,
      col: 17,
    },
    { bg: "bg-purple-950", n: 86, s: "Rn ", name: " Radon", row: 6, col: 18 },
    { bg: "bg-pink-300", n: 87, s: "Fr ", name: "Francium ", row: 7, col: 1 },
    { bg: "bg-orange-300", n: 88, s: "Ra ", name: "Radium ", row: 7, col: 2 },
    { bg: " bg-pink-500 ", n: "", s: "89-103 ", name: " ", row: 7, col: 3 },
    {
      bg: "bg-yellow-400 ",
      n: 104,
      s: "Rf ",
      name: " Rutherfordium",
      row: 7,
      col: 4,
    },
    {
      bg: "bg-yellow-400 ",
      n: 105,
      s: "Db ",
      name: "Dubnium ",
      row: 7,
      col: 5,
    },
    {
      bg: "bg-yellow-400 ",
      n: 106,
      s: " Sg",
      name: "Seaborgium ",
      row: 7,
      col: 6,
    },
    {
      bg: "bg-yellow-400 ",
      n: 107,
      s: "Bh ",
      name: "Bohrium ",
      row: 7,
      col: 7,
    },
    {
      bg: "bg-yellow-400 ",
      n: 108,
      s: "Hs ",
      name: "Hassium ",
      row: 7,
      col: 8,
    },
    {
      bg: "bg-yellow-400 ",
      n: 109,
      s: "Mt ",
      name: "Meitnerium ",
      row: 7,
      col: 9,
    },
    {
      bg: "bg-yellow-400 ",
      n: 110,
      s: " Ds",
      name: "Darmstadtium ",
      row: 7,
      col: 10,
    },
    {
      bg: "bg-yellow-400 ",
      n: 111,
      s: " Rg",
      name: " Roentgenium",
      row: 7,
      col: 11,
    },
    {
      bg: "bg-yellow-400 ",
      n: 112,
      s: "Cn ",
      name: "Copernicium ",
      row: 7,
      col: 12,
    },
    {
      bg: "bg-green-300 ",
      n: 113,
      s: "Nh ",
      name: "Nihonium ",
      row: 7,
      col: 13,
    },
    {
      bg: "bg-green-300 ",
      n: 114,
      s: "Fl ",
      name: "Flerovium ",
      row: 7,
      col: 14,
    },
    {
      bg: "bg-green-300 ",
      n: 115,
      s: "Mc ",
      name: "Moscovium ",
      row: 7,
      col: 15,
    },
    {
      bg: "bg-green-300 ",
      n: 116,
      s: "Lv ",
      name: "Livermorium ",
      row: 7,
      col: 16,
    },
    {
      bg: "bg-purple-800",
      n: 117,
      s: " Ts",
      name: " Tennessine",
      row: 7,
      col: 17,
    },
    {
      bg: "bg-purple-950",
      n: 118,
      s: "Og ",
      name: " Oganesson",
      row: 7,
      col: 18,
    },
    {
      bg: "bg-purple-500 ",
      n: 57,
      s: "La",
      name: "Lanthanum ",
      row: 9,
      col: 3,
    },
    { bg: "bg-purple-500 ", n: 58, s: "Ce", name: "Cerium ", row: 9, col: 4 },
    {
      bg: "bg-purple-500 ",
      n: 59,
      s: "Pr",
      name: "Praseodymium ",
      row: 9,
      col: 5,
    },
    {
      bg: "bg-purple-500 ",
      n: 60,
      s: "Nd",
      name: "Neodymium ",
      row: 9,
      col: 6,
    },
    {
      bg: "bg-purple-500 ",
      n: 61,
      s: "Pm",
      name: " Promethium",
      row: 9,
      col: 7,
    },
    { bg: "bg-purple-500 ", n: 62, s: "Sm", name: "Samarium ", row: 9, col: 8 },
    { bg: "bg-purple-500 ", n: 63, s: "Eu", name: " Europium", row: 9, col: 9 },
    {
      bg: "bg-purple-500 ",
      n: 64,
      s: "Gd",
      name: " Gadolinium",
      row: 9,
      col: 10,
    },
    { bg: "bg-purple-500 ", n: 65, s: "Tb", name: " Terbium", row: 9, col: 11 },
    {
      bg: "bg-purple-500 ",
      n: 66,
      s: "Dy",
      name: "Dysprosium ",
      row: 9,
      col: 12,
    },
    { bg: "bg-purple-500 ", n: 67, s: "Ho", name: "Holmium ", row: 9, col: 13 },
    { bg: "bg-purple-500 ", n: 68, s: "Er", name: " Erbium", row: 9, col: 14 },
    { bg: "bg-purple-500 ", n: 69, s: "Tm", name: " Thulium", row: 9, col: 15 },
    {
      bg: "bg-purple-500 ",
      n: 70,
      s: "Yb",
      name: " Ytterbium",
      row: 9,
      col: 16,
    },
    {
      bg: "bg-purple-500 ",
      n: 71,
      s: "Lu",
      name: " Lutetium",
      row: 9,
      col: 17,
    },
    {
      bg: " bg-pink-500 ",
      n: 89,
      s: "Ac ",
      name: "Actinium ",
      row: 10,
      col: 3,
    },
    { bg: " bg-pink-500 ", n: 90, s: "Th ", name: "Thorium ", row: 10, col: 4 },
    {
      bg: " bg-pink-500 ",
      n: 91,
      s: "Pa ",
      name: "Protactinium ",
      row: 10,
      col: 5,
    },
    { bg: " bg-pink-500 ", n: 92, s: " U", name: "Uranium ", row: 10, col: 6 },
    {
      bg: " bg-pink-500 ",
      n: 93,
      s: " Np",
      name: "Neptunium",
      row: 10,
      col: 7,
    },
    {
      bg: " bg-pink-500 ",
      n: 94,
      s: "Pu ",
      name: "Plutonium ",
      row: 10,
      col: 8,
    },
    {
      bg: " bg-pink-500 ",
      n: 95,
      s: "Am ",
      name: "Americium",
      row: 10,
      col: 9,
    },
    { bg: " bg-pink-500 ", n: 96, s: " Cm", name: "Curium", row: 10, col: 10 },
    {
      bg: " bg-pink-500 ",
      n: 97,
      s: "Bk ",
      name: "Berkelium",
      row: 10,
      col: 11,
    },
    {
      bg: " bg-pink-500 ",
      n: 98,
      s: "Cf ",
      name: "Californium ",
      row: 10,
      col: 12,
    },
    {
      bg: " bg-pink-500 ",
      n: 99,
      s: "Es ",
      name: "Einsteinium ",
      row: 10,
      col: 13,
    },
    {
      bg: " bg-pink-500 ",
      n: 100,
      s: " Fm",
      name: "Fermium",
      row: 10,
      col: 14,
    },
    {
      bg: " bg-pink-500 ",
      n: 101,
      s: " Md",
      name: "Mendelevium",
      row: 10,
      col: 15,
    },
    {
      bg: " bg-pink-500 ",
      n: 102,
      s: "No ",
      name: "Nobelium ",
      row: 10,
      col: 16,
    },
    {
      bg: " bg-pink-500 ",
      n: 103,
      s: "Lr ",
      name: "Lawrencium",
      row: 10,
      col: 17,
    },
  ];

  return (
    <>
      <div className="flex justify-center items-center overflow-auto">
        <div className="p-4 overflow-x-auto">
          <h1
            className="text-white text-5xl p-5 flex justify-center items-center font-serif
               transition-all duration-300
               hover:drop-shadow-[0_0_12px_rgba(255,255,255,0.9)]"
          >
            Periodic Table
          </h1>
          <div className="grid grid-cols-[repeat(18,70px)] grid-rows-[repeat(10,70px)]  gap-2">
            {elements.map((el) => (
              <div
                key={el.n}
                className={`border rounded flex flex-col justify-center items-center text-sm ${el.bg} 
                transition-transform-duration-500 hover:scale-150 border
                 border-white/30 hover:border-white hover:shadow-[0_0_15px_4px_rgba(255,255,255,0.9)] transitio-all duration-200`}
                style={{
                  gridColumnStart: el.col,
                  gridRowStart: el.row,
                }}
              >
                <span className="text-xs self-start ml-1">{el.n}</span>
                <span className="text-xl font-bold">{el.s}</span>
                <span className="text-[10px]">{el.name}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </>
  );
}
